<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Product>welocalize OPAL [Beta]</Product>
        <Description>welocalize OPAL is an AI-powered localization platform used to translate and manage multilingual content at scale</Description>
        <Version>1.0.2</Version>
        <AssemblyName>Apps.Opal</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Blackbird.Applications.Sdk.Common" Version="2.14.0" />
        <PackageReference Include="Blackbird.Applications.Sdk.Utils" Version="1.1.0-rc.8709" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource CopyToOutputDirectory="Always" Include="image\icon.png" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="image\" />
    </ItemGroup>

</Project>
